apiVersion: v1
kind: PersistentVolume
metadata:
  name: database
  labels:
    volume: my-volume
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  nfs:
    server: 192.168.0.1
    path: "/exports"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      volume: my-volume

---

# Why create a ReplicaSet to manage a single Pod (singleton)? The ReplicaSet
# ensures that the Pod is rescheduled in the event of Node failures. If it were
# a bare Pod and the Node failed, the Pod would simply die — it needs a higher
# level controller (like ReplicaSet or Deployment) for this case.

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: database
          image: mysql
          resources:
            requests:
              cpu: 1
              memory: 2Gi
          env:
            # Environment variables are not a best practice for security.
            - name: MYSQL_ROOT_PASSWORD
              value: some-password-here
          livenessProbe:
            tcpSocket:
              port: 3306
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: database
              # /var/lib/mysql is where MySQL stores its databases
              mountPath: "/var/lib/mysql"
      volumes:
        - name: database
          persistentVolumeClaim:
            claimName: database

---

apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
    - port: 3306
      protocol: TCP
  selector:
    app: mysql