# Example of a cluster secret store for AWS Secret Manager.
# NOTE: This example assumes Pod Identity addon is installed on the EKS cluster
# and so it doesn't need IRSAs (IAM Roles for Service Accounts).

apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secretsmanager
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-central-1