# This manifest sets the Postgres password but it's obviously for learning
# purposes since it exposes the password in plain text and it's commited on a
# public repo, never do this in prod!

apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: postgres
type: Opaque
# String data to write the password as a literal string and not base 64 encoded.
stringData:
  password: password
