apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: postgres

spec:
  serviceName: postgres     # Must match the Service name.
  replicas: 3
  selector:
    matchLabels:
      app: postgres

  template:
    metadata:
      labels:
        app: postgres
    spec:
      terminationGracePeriodSeconds: 30

################################################################################
# Container
################################################################################

      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            # PGDATA needs to be mounted on an empty subdirectory otherwise
            # Postgres refuses to start (common when trying to mount on an ext4
            # directory that includes by default a "lost+found" subdirectory).
            # This is why we mount it into the var/lib/postgresql/data and not
            # /var/lib/postgresql/data/pgdata
            - name: data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: "2"
              memory: 2Gi
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
            initialDelaySeconds: 30
            periodSeconds: 15

################################################################################
# PVCs setup
################################################################################

  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: postgres-gp3-encrypted
        resources:
          requests:
            storage: 20Gi